### ISSUE TITLE
README protocol information

### ISSUE THREAD

**Issue by ryleu** [Ridderrasmus/RPVoiceChat#131]
I would love to see some info on what protocol RPVoiceChat works over, namely TCP / UDP. I'm currently configuring my firewall and I don't know which to allow, though I'm going to try UDP first.

**Comment by Ridderrasmus** [comment]
I've quietly begun to work on the mod ever so slowly again so you're just in time for me to address this.

I agree this should probably be more clear but just to outline it for you here and now:

As a standard without changing the mod server configurations the mod simply uses the games built-in networking and thus doesn't need to have anything changed regarding your firewall. **However** if you do happen to experience slowdown it _may_ benefit you to enable using UDP networking separately. This is marked as the UseCustomNetworkServers config option.

Now this _still_ doesn't necessarily mean you need to open ports manually as UPnP is also functional by default so it will ask your router for a usable port. This can also be overridden to manually determine a port by changing the ManualPortForwarding config option.

**Keep in mind that when changing any of the default connection settings like manual port forwarding and such setup becomes your own responsibility. The mod should work out of the box if you do not mess with any settings.**

**Comment by ryleu** [comment]
I'm using a proxy so UPnP wasn't an option for me in the first place. Thanks for the information!
