### ISSUE TITLE
Add french translation.

### ISSUE THREAD

**Issue by Vlammar** [Ridderrasmus/RPVoiceChat#81]
I can help you in doing the french translation of the plugin:
For the file assets/rpvoicechat/lang/en.json
in french it will be:  (be carefull we have some special char in french such as "é ç â" ... they may be bugged if the plugin and game couldn't handle them) 
```
{
  "item-handbell": "Clochette",
  "item-royalhorn": "Cor royal",
  "item-royalhornhandle": "Manche de cor royal",
  "item-royalhornhead": "Tête de cor royal",
  "item-handheldradio": "Radio portative",
  "item-telegraphwire": "Câble de télégraphe",
  "item-radiocase": "Boitier radio",

  "itemdesc-handbell": "Une petite clochette. L'argent de la cloche semble émettre un étrange scintillement violet ...",

  "block-callbell": "Cloche d'appel",

  "blockdesc-callbell": "Une petite cloche que l'on peut sonner pour appeler une personne."

}
```
(By the way there is a miss print in english with the handbell item description)

I haven't found the file for the settings menu but i can also do it for you.

**Comment by Dmitry221060** [comment]
Hello, thank you for contributing to our mod! 
[Here](https://github.com/Ridderrasmus/RPVoiceChat/blob/5a7e563f01f567fdc7c0c1a1e3669588505fe2d3/assets/rpvoicechat/lang/en.json) is a file for settings menu, if you want to translate it as well.
If you can open a PR with your changes we will be happy to accept it ^_^

As for handbell item description, "purplep" is an Easter egg referencing author of item and block models for the mod - @Faithfulshot (Purplep_)

**Comment by Vlammar** [comment]
I will open a PR but I have not setup vintage story for modding right now so I won't be able to test the PR before hand.
For the ester egg sadly there is no close words in french for it. "Pourpre" is a more redish color that you find on the shell of red onions.

**Comment by Dmitry221060** [comment]
Don't worry, I will test the translations to make sure they are applied correctly and don't cause any rendering issues~
It is fine if you omit the Easter egg so you can use whatever fits the best in your opinion

**Comment by Faithfulshot** [comment]
Yup, the Easter egg is just there for the sake of being there, so there's no need to go out of your way to rewrite it if it doesn't make sense ^^
Also thank you very much for the help 😊😊

**Comment by Ridderrasmus** [comment]
Thank you so much for the help with the translation! Very much appreciated! ❤️
